//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffmpegForRTMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamInfo
    {
        public int ID { get; set; }
        public string CamName { get; set; }
        public string Owner { get; set; }
        public string SN { get; set; }
        public string Captcha { get; set; }
        public string Pwd { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> H { get; set; }
        public string OperatingState { get; set; }
        public string Remark { get; set; }
        public string RTMP { get; set; }
        public string HLS { get; set; }
        public Nullable<int> Channel { get; set; }
        public string RTMPHd { get; set; }
        public string HLSHd { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Controller { get; set; }
        public Nullable<int> CamType { get; set; }
    }
}
