//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffmpegForRTMP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartBuildingEntities : DbContext
    {
        public SmartBuildingEntities()
            : base("name=SmartBuildingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CamInfo> CamInfo { get; set; }
        public DbSet<CompanyInfo> CompanyInfo { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<SysLog> SysLog { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<VideoPath> VideoPath { get; set; }
        public DbSet<CamRTMP> CamRTMP { get; set; }
        public DbSet<WebPurviewMenu> WebPurviewMenu集 { get; set; }
        public DbSet<WebUserPurview> WebUserPurview集 { get; set; }
    }
}
